### PR TITLE
Season 5

### PR DESCRIPTION
**Pull request by Pausbe**
Commit #97 instead

## Changelog

**- Added Season 5 Weapons**
- **Assault Rifle:** FR Avancer (Launch)
- **Sniper Rifle:** Carrack .300 (Launch)
- **Assault Rifle:** M13C (In-Season)

### CODE REVIEW

**Comment by Pausbe** [comment]
For some reason, the camos I added for the S5 weapons show up as 'undefined' when hovering over them. I have no idea why this is, but it seems like the issue is stemming from `src\data\requirements\weapons\assaultRifles.js` and `src\data\requirements\weapons\sniperRifles.js`. Could be a Visual Studio Code setting on my side that's causing it, since I had to reinstall it ¯\_(ツ)_/¯

Other than that, the pull request is ready.

**Comment by Voigtus** [comment]
Just a wild guess, but might it be, that you haven't added the camouflages to the src/assets/camouflages folder?
At least I can not find them in your PR

**Comment by Voigtus** [comment]
Hai  @Pausbe ,
just a heads up. Since I did not want to commit over your changes, I created a new PR based on your changes.

**Comment by Pausbe** [comment]
> Just a wild guess, but might it be, that you haven't added the camouflages to the src/assets/camouflages folder?
> 
> At least I can not find them in your PR 

Fuck. I figured out what the issue is now. Didn't add the requirements for the individual camos. I knew I missed something cause I made that pull request pretty fast. 😅

**Comment by Pausbe** [comment]
> Hai  @Pausbe ,
> 
> just a heads up. Since I did not want to commit over your changes, I created a new PR based on your changes.
> 
> 

Thanks! Feel free to commit over my changes if something like this happens in the future. I'm just going to close my PR since yours is already done 👍

**Pull request closed without merging**
