### PR TITLE
Calling card fix

### PR DESCRIPTION
**Pull request by C0deS3rp3nt**
Regarding the latest commit for calling cards, Both Calling_cards.js and operator.js weren't update so they displayed "challenges.calling_cards.operator.*name*" and not clickable, fixed that by adding both GoD and VS to calling_cards.js and fixed both subcatagory type so they display the proper requirements and can be clicked on.

### CODE REVIEW

**Comment by C0deS3rp3nt** [comment]
I didn't read any pull requests this was already pointed out in #119

**Comment by jamesallnutt** [comment]
my fault @C0deS3rp3nt - i should have been clearer in #119 ! I messed up the type, which broke those 2 cards. I did some testing after #119 which involved clicking every single card 😂 was a long test but should all be good now.

**Comment by C0deS3rp3nt** [comment]
> my fault @C0deS3rp3nt - i should have been clearer in #119 ! I messed up the type, which broke those 2 cards. I did some testing after #119 which involved clicking every single card 😂 was a long test but should all be good now.

Oh god no! Don't apologize @jamesallnutt I have a tendency not to thoroughly look at things before I do anything, I'm glad you caught that as well. Good stuff. aha

**Comment by jamesallnutt** [comment]
My fault, I broke it trying to add all the Prestige Calling Cards - also want to blame IW a little bit, because they changed some of the calling cards around in season 3-4 so the names changed.

**Comment by C0deS3rp3nt** [comment]
> My fault, I broke it trying to add all the Prestige Calling Cards - also want to blame IW a little bit, because they changed some of the calling cards around in season 3-4 so the names changed.

Honestly, I blame IW in general for most of the stuff they add and change lol. Creates extra work, we live and learn. 

I'm going to be honest, I don't normally use github to contribute or commit to projects so this is all confusing to me, I need to open my eyes more often aha!

**Pull request closed without merging**
