### PR TITLE
Assault Rifle - Camo Images

### PR DESCRIPTION
**Pull request by MaxJW**
Includes:
* Remaining camouflage images
* Fixes TAQ-56 camo name (Icepick)
* Fixes Rip N' Tear image filename (needed a ')

All images are in 1x1 format. Those in commit 75587f1 were edited using photopea's healing tool to remove the padlock and progress bar (as I haven't unlocked them yet!), but I think they do the job, something to check though!

### CODE REVIEW

**Comment by sol3uk** [comment]
I think the name changes would need to be included in the `camouflageNameChanges.js` so progress is carried over.

**Comment by sol3uk** [comment]
@carlssonemil were all the images from https://github.com/carlssonemil/orion/issues/34#issuecomment-1328159678 added to the app so far? Wouldn't want any duplicated effort if we already have the images 😄

**Comment by MaxJW** [comment]
> I think the name changes would need to be included in the `camouflageNameChanges.js` so progress is carried over.

I've updated that in [9a40dfd](https://github.com/carlssonemil/orion/pull/41/commits/9a40dfd76290af0e237702c6c288a907086ecfc1)!


> @carlssonemil were all the images from [#34 (comment)](https://github.com/carlssonemil/orion/issues/34#issuecomment-1328159678) added to the app so far? Wouldn't want any duplicated effort if we already have the images 😄

Had no idea that existed haha, I'll take a look just now, I imagine definitely some duplicated effort by the looks of things 😅

**Comment by MaxJW** [comment]
Looks like I'm safe on the images front, the additions I have made were not in those zip files! Though I did notice this: https://github.com/carlssonemil/orion/issues/34#issuecomment-1328343280

@cpjet64 Need any help with that? 😄 (wrote the wrong username there, sorry!)

**Comment by sol3uk** [comment]
Nice one @MaxJW! I've had a mess around & quick test, all looks good! We will have to wait for the bossman to approve 😄 in the meantime I'll take a quick look and nit-pick as per usual (sorry in advance!).

Is the jungle-digital.png the correct one for the assault rifle and are we sure it's not being mixed up with the camo of the same name for the RPG? (I can double check this later but you might already know the answer to this)

@carlssonemil I was reading up around slug casing, is the apostrophe a [valid character](https://docs.orchardproject.net/en/latest/Documentation/Slugs/)? Would we need to normalise this?

**Comment by carlssonemil** [comment]
Nice! 🚀 

> @carlssonemil were all the images from [#34 (comment)](https://github.com/carlssonemil/orion/issues/34#issuecomment-1328159678) added to the app so far? Wouldn't want any duplicated effort if we already have the images 😄

Yes, I've added all the images in the .zip files, took a while to crop them all! 😄 

> @carlssonemil I was reading up around slug casing, is the apostrophe a [valid character](https://docs.orchardproject.net/en/latest/Documentation/Slugs/)? Would we need to normalise this?

Good question. It seems to work in the preview build though so it should be fine. Let's just leave it as is for now and change it later if we encounter any issues 😄

**Review by carlssonemil — APPROVED** [review]

**Comment by cpjet64** [comment]
> Looks like I'm safe on the images front, the additions I have made were not in those zip files! Though I did notice this: [#34 (comment)](https://github.com/carlssonemil/orion/issues/34#issuecomment-1328343280)
> 
> @cpjet64 Need any help with that? 😄 (wrote the wrong username there, sorry!)

YES! PLEASE! there are 42,261 image files and the filenames are all hashed so you have to look at every pic individually. I believe the original dimensions are 256x256 and they are all png.

**Comment by carlssonemil** [comment]
> 42,261 image files

👀

**Comment by MaxJW** [comment]
> YES! PLEASE! there are 42,261 image files and the filenames are all hashed so you have to look at every pic individually. I believe the original dimensions are 256x256 and they are all png.

No worries! Where should I look? How do I look? 😆 If you could give me some guidance I'd love to help out!

**Comment by cpjet64** [comment]
Remember though that is all game images in total xD. For anyone who wants to help sort through them I can upload the complete collection of images and then share the link on a individual basis via email or dm.

**Comment by MaxJW** [comment]
> Probably move this chat to discord @carlssonemil @cpjet64 @MaxJW

Sounds good to me! Feel free to send a message to me there, or get a group setup of some kind! SirVoxel#7719

**Pull request merged**
