### PR TITLE
[Feature] Weapon mastery tracking

### LINKED ISSUE #37: Weapon Mastery Tracking (Feature Suggestion)
It would be nice to have weapon mastery tracking, similar to the Damascus tracker.
They've also made it simple this time around, only requiring kills with a specific camo equipped.

image

### PR DESCRIPTION
**Pull request by carlssonemil**
Adds tracking for weapon mastery as suggested in #37.

- Fixes #37

### CODE REVIEW

**Comment by carlssonemil** [comment]
@CrazyIsEasy, is this what you were thinking about? 😄

**Comment by sol3uk** [comment]
There's no way to unlock 100% mastery whilst the "Coming Soon" weapon Chimera is on there 😬

**Comment by sol3uk** [comment]
image

All mastery challenge texts on the homepage seem broken.

**Comment by sol3uk** [comment]
Do you reckon it would be worth adding a tooltip info like the weapons page to tell the user more about the mastery page?
Not everyone will know 😄 

image

**Comment by sol3uk** [comment]
(Sorry for the spam) 

brave_3Gf9PKWuIa

Seems like there is some sort of CSS issue when completing a camo or double clicking to complete a gun.
Not sure if this is just a preview build issue but it doesn't happen on the mastery page, I assume because this bug probably relates to image default sizing (because there's no camo images on the mastery page) and the image reverting to its normal size for a split second maybe?

**Comment by carlssonemil** [comment]
Fixed a bunch of stuff! Nice finds! 😄 

I'll take a look at the image issue tomorrow!

**Comment by Pausbe** [comment]
> @CrazyIsEasy, is this what you were thinking about? 😄

Yep! Appreciate you working on it so fast :heart:

**Pull request merged**
