### PR TITLE
Season 6 - New weapons

### PR DESCRIPTION
**Pull request by LTKort**
old pr #105

@carlssonemil  Removed the package-lock.json

### CODE REVIEW

**Review by carlssonemil — APPROVED** [review]
❤️

**Comment by carlssonemil** [comment]
Not sure why your `package-lock.json` is different from mine 🤷 I'll maybe look into it sometime! I'm working on the tracker for the new CoD so it's not high on my priority list though 😅

**Comment by LTKort** [comment]
> Not sure why your `package-lock.json` is different from mine 🤷 I'll maybe look into it sometime! I'm working on the tracker for the new CoD so it's not high on my priority list though 😅 

The lock file should not be an issue, I guess it just from a package update, it's just minor updates, for major updates the package.json file would be affected.

Side note; have you checked out Bun? Instead of NOm?

And if you need any help with the new cod tracker, I would love to help!

**Comment by carlssonemil** [comment]
Bun is nice! I've switched over to Yarn for most new projects though, handles packages much better than NPM.

I'm mostly just gathering info right now, much of the boilerplate code is already set up [here](https://github.com/carlssonemil/mw3) 😄 You're more than welcome to help gather information on how the camouflage system will work and posting it in the [discussions](https://github.com/carlssonemil/mw3/discussions)!

**Comment by LTKort** [comment]
> Bun is nice! I've switched over to Yarn for most new projects though, handles packages much better than NPM.
> 
> 
> 
> I'm mostly just gathering info right now, much of the boilerplate code is already set up [here](https://github.com/carlssonemil/mw3) 😄 You're more than welcome to help gather information on how the camouflage system will work and posting it in the [discussions](https://github.com/carlssonemil/mw3/discussions)!

Thanks, will do! Any change to merge PR #108 yet?

**Comment by carlssonemil** [comment]
Merged!

**Pull request merged**
